import Head from "next/head";
import Image from "next/image";
import { useEffect, useState } from "react";
import Movie from "../../components/movie.js";

import styled from "./search.module.scss";
import Link from "next/link";
import { useRouter } from "next/router";
import { AnimatePresence, motion, useAnimation } from "framer-motion";

import Header from "../../components/header.jsx";
import Searchresult from "../../components/searchresult.js";

const boxVariants = {
  normal: {
    scale: 1,
  },
  hover: {
    scale: 1.3,
    y: -50,
    transition: {
      delay: 0.1,
      duration: 0.2,
      type: "tween",
    },
  },
};

export default function Search({ data }) {
  const { result } = data;
  const router = useRouter();
  console.log(router.query.keyword);
  const [filteredData, setFilteredData] = useState();

  useEffect(() => {
    const getSearchData = result.filter((movie) => {
      return movie.properties.title
        .toLowerCase()
        .includes(router.query.keyword.toLowerCase());
    });
    setFilteredData(getSearchData);
  }, [router.query.keyword]);
  console.log(filteredData);

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={styled.banner}></div>
      <main className={styled.container}>
        <Header />
        {/* <h1 className={styled.title} onClick={incraseIndex}>
          Welcome to <a href="https://nextjs.org">Next.js!</a>
        </h1> */}

        <div className={styled.slider}>
          <div className={styled.gridcontainer}>
            {filteredData.length > 0 ? (
              filteredData?.map((movie) => (
                <motion.div
                  variants={boxVariants}
                  initial="normal"
                  whileHover={"hover"}
                  className={styled.box}
                  transition={{ type: "tween" }}
                  key={movie.uid}
                >
                  <Searchresult movie={movie} key={movie.uid} />
                </motion.div>
              ))
            ) : (
              <div className={styled.noresult}>
                <h1>No result found</h1>
              </div>
            )}
          </div>
        </div>
      </main>

      <footer className={styled.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
}

export async function getServerSideProps(context) {
  console.log(context.query, "query");
  const res = await fetch(`https://www.swapi.tech/api/films`);
  const data = await res.json();

  if (!data) {
    return {
      notFound: true,
    };
  }

  return {
    props: { data }, // will be passed to the page component as props
  };
}
